version: 1.0.{build}

environment:
  secured_passwd:
    secure: lBislJUl6RP/4mh6NOGZcA==

install:
  - ps: wget https://s3.amazonaws.com/biibinaries/thirdparty/cmake-3.0.2-win32-x86.zip -OutFile cmake.zip
  - cmd: echo "Unzipping cmake..."
  - cmd: 7z x cmake.zip -o"C:\Program Files (x86)\" -y > nul
  - cmd: set PATH=%PATH:CMake 2.8\bin=%;C:\Program Files (x86)\cmake-3.0.2-win32-x86\bin
  - cmd: cmake --version
  - cmd: echo "Downloading biicode..."
  - ps: wget http://www.biicode.com/downloads/latest/win -OutFile bii-win.exe
  - cmd: bii-win.exe /VERYSILENT
  - cmd: set PATH=%PATH%;C:\Program Files (x86)\BiiCode\bii
  - cmd: bii -v
  - cmd: del bii-win.exe
  - cmd: del cmake.zip

before_build:
  - cmd: bii init myproject
  - cmd: cd myproject
  - cmd: bii new lasote/docker_client
  # Yes, I know, sure this move can be improved
  - cmd: move ..\* blocks\lasote\docker_client\
  - cmd: move ..\example blocks\lasote\docker_client\
  - cmd: bii cpp:configure -G "Visual Studio 12"

build_script:
  - cmd: bii cpp:build

test_script:
  - cmd: ls bin\lasote_docker_client_example_main.exe

# to run your custom scripts instead of provider deployments
deploy_script:
  - cmd: bii user lasote -p %secured_passwd%
  - cmd: bii publish || dir # Ignore output

